apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: elb-example
  name: elb-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elb-example
      name: elb-example
    spec:
      containers:
        - name: elb-example
          image: "kelseyhightower/elb-example:1.0.0"
        - name: kubectl
          image: "kelseyhightower/kubectl:1.4.0"
          args:
            - "proxy"
