apiVersion: v1
kind: Service
metadata:
  labels:
    app: elb-example
  name: elb-example
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: elb-example
